version: "3.0"
services:
  phpfpm:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    volumes:
      - ./src/phpmyadmin:/usr/share/nginx/html/phpmyadmin    
    extra_hosts: 
      host.app: 192.168.100.6

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports: 
      - 8000:80
    volumes: 
      - ./src/phpmyadmin:/usr/share/nginx/html/phpmyadmin
      - ./nginx-phpmyadmin.conf:/etc/nginx/conf.d/default.conf
